export interface NFLPlayer {
  id: string
  name: string
  position: string
  team: string
  number: string
  projected: number
  image: string
  tier: "gold" | "green" | "blue" | "orange" | "purple" | "red"
  stats: {
    passing?: number
    rushing?: number
    receiving?: number
    blocking?: number
    tackling?: number
    coverage?: number
  }
  adp: number // Average Draft Position
  rank: number
}

export const nflPlayerDatabase: NFLPlayer[] = [
  // Quarterbacks
  {
    id: "patrick-mahomes",
    name: "Patrick Mahomes",
    position: "QB",
    team: "KC",
    number: "15",
    projected: 24.8,
    image: "/patrick-mahomes-chiefs.jpg",
    tier: "gold",
    stats: { passing: 98, rushing: 55 },
    adp: 1.2,
    rank: 1,
  },
  {
    id: "josh-allen",
    name: "Josh Allen",
    position: "QB",
    team: "BUF",
    number: "17",
    projected: 24.5,
    image: "/josh-allen-bills.jpg",
    tier: "gold",
    stats: { passing: 96, rushing: 72 },
    adp: 1.5,
    rank: 2,
  },
  {
    id: "lamar-jackson",
    name: "Lamar Jackson",
    position: "QB",
    team: "BAL",
    number: "8",
    projected: 24.2,
    image: "/lamar-jackson-ravens.jpg",
    tier: "gold",
    stats: { passing: 92, rushing: 88 },
    adp: 1.8,
    rank: 3,
  },
  {
    id: "jalen-hurts",
    name: "Jalen Hurts",
    position: "QB",
    team: "PHI",
    number: "1",
    projected: 23.9,
    image: "/jalen-hurts-eagles.jpg",
    tier: "gold",
    stats: { passing: 90, rushing: 80 },
    adp: 2.1,
    rank: 4,
  },
  {
    id: "caleb-williams",
    name: "Caleb Williams",
    position: "QB",
    team: "CHI",
    number: "18",
    projected: 23.7,
    image: "/caleb-williams-chicago-bears-quarterback-throwing.jpg",
    tier: "gold",
    stats: { passing: 88, rushing: 65 },
    adp: 2.5,
    rank: 5,
  },
  {
    id: "joe-burrow",
    name: "Joe Burrow",
    position: "QB",
    team: "CIN",
    number: "9",
    projected: 22.1,
    image: "/joe-burrow-bengals.jpg",
    tier: "green",
    stats: { passing: 94, rushing: 35 },
    adp: 3.2,
    rank: 6,
  },
  {
    id: "cj-stroud",
    name: "C.J. Stroud",
    position: "QB",
    team: "HOU",
    number: "7",
    projected: 21.8,
    image: "/cj-stroud-texans.jpg",
    tier: "green",
    stats: { passing: 91, rushing: 40 },
    adp: 3.5,
    rank: 7,
  },
  {
    id: "tua-tagovailoa",
    name: "Tua Tagovailoa",
    position: "QB",
    team: "MIA",
    number: "1",
    projected: 21.5,
    image: "/tua-tagovailoa-miami-dolphins-quarterback.jpg",
    tier: "green",
    stats: { passing: 89, rushing: 35 },
    adp: 4.1,
    rank: 8,
  },
  {
    id: "brock-purdy",
    name: "Brock Purdy",
    position: "QB",
    team: "SF",
    number: "13",
    projected: 20.8,
    image: "/brock-purdy-49ers-quarterback.jpg",
    tier: "blue",
    stats: { passing: 87, rushing: 38 },
    adp: 4.8,
    rank: 9,
  },
  {
    id: "jordan-love",
    name: "Jordan Love",
    position: "QB",
    team: "GB",
    number: "10",
    projected: 20.5,
    image: "/jordan-love-packers.jpg",
    tier: "blue",
    stats: { passing: 86, rushing: 42 },
    adp: 5.1,
    rank: 10,
  },

  // Running Backs
  {
    id: "christian-mccaffrey",
    name: "Christian McCaffrey",
    position: "RB",
    team: "SF",
    number: "23",
    projected: 21.5,
    image: "/christian-mccaffrey-49ers.jpg",
    tier: "gold",
    stats: { rushing: 95, receiving: 88 },
    adp: 1.1,
    rank: 1,
  },
  {
    id: "saquon-barkley",
    name: "Saquon Barkley",
    position: "RB",
    team: "PHI",
    number: "26",
    projected: 18.6,
    image: "/saquon-barkley-eagles-running-back-action.jpg",
    tier: "green",
    stats: { rushing: 90, receiving: 75 },
    adp: 1.8,
    rank: 2,
  },
  {
    id: "bijan-robinson",
    name: "Bijan Robinson",
    position: "RB",
    team: "ATL",
    number: "7",
    projected: 18.9,
    image: "/bijan-robinson-falcons.jpg",
    tier: "green",
    stats: { rushing: 92, receiving: 72 },
    adp: 1.9,
    rank: 3,
  },
  {
    id: "kyren-williams",
    name: "Kyren Williams",
    position: "RB",
    team: "LAR",
    number: "23",
    projected: 17.2,
    image: "/kyren-williams-rams-running-back.jpg",
    tier: "blue",
    stats: { rushing: 85, receiving: 65 },
    adp: 2.5,
    rank: 4,
  },
  {
    id: "jordan-mason",
    name: "Jordan Mason",
    position: "RB",
    team: "SF",
    number: "44",
    projected: 16.0,
    image: "/jordan-mason-49ers-running-back.jpg",
    tier: "green",
    stats: { rushing: 82, receiving: 55 },
    adp: 4.2,
    rank: 5,
  },
  {
    id: "james-conner",
    name: "James Conner",
    position: "RB",
    team: "ARI",
    number: "6",
    projected: 14.8,
    image: "/james-conner.jpg",
    tier: "green",
    stats: { rushing: 82, receiving: 55 },
    adp: 5.1,
    rank: 6,
  },
  {
    id: "derrick-henry",
    name: "Derrick Henry",
    position: "RB",
    team: "BAL",
    number: "22",
    projected: 17.8,
    image: "/derrick-henry-ravens.jpg",
    tier: "green",
    stats: { rushing: 94, receiving: 45 },
    adp: 2.2,
    rank: 7,
  },
  {
    id: "jahmyr-gibbs",
    name: "Jahmyr Gibbs",
    position: "RB",
    team: "DET",
    number: "26",
    projected: 17.5,
    image: "/jahmyr-gibbs-lions.jpg",
    tier: "blue",
    stats: { rushing: 86, receiving: 80 },
    adp: 2.8,
    rank: 8,
  },
  {
    id: "jonathan-taylor",
    name: "Jonathan Taylor",
    position: "RB",
    team: "IND",
    number: "28",
    projected: 17.1,
    image: "/jonathan-taylor-colts-running-back.jpg",
    tier: "green",
    stats: { rushing: 91, receiving: 62 },
    adp: 2.3,
    rank: 9,
  },
  {
    id: "josh-jacobs",
    name: "Josh Jacobs",
    position: "RB",
    team: "GB",
    number: "8",
    projected: 16.5,
    image: "/josh-jacobs-packers-running-back.jpg",
    tier: "blue",
    stats: { rushing: 87, receiving: 58 },
    adp: 3.1,
    rank: 10,
  },
  {
    id: "travis-etienne",
    name: "Travis Etienne Jr.",
    position: "RB",
    team: "JAX",
    number: "1",
    projected: 16.2,
    image: "/travis-etienne-jaguars-running-back.jpg",
    tier: "blue",
    stats: { rushing: 84, receiving: 70 },
    adp: 3.4,
    rank: 11,
  },
  {
    id: "kenneth-walker",
    name: "Kenneth Walker III",
    position: "RB",
    team: "SEA",
    number: "9",
    projected: 15.8,
    image: "/kenneth-walker-seahawks-running-back.jpg",
    tier: "green",
    stats: { rushing: 86, receiving: 52 },
    adp: 3.8,
    rank: 12,
  },
  {
    id: "rachaad-white",
    name: "Rachaad White",
    position: "RB",
    team: "TB",
    number: "29",
    projected: 15.2,
    image: "/rachaad-white-buccaneers-running-back.jpg",
    tier: "blue",
    stats: { rushing: 80, receiving: 75 },
    adp: 4.5,
    rank: 13,
  },
  {
    id: "alvin-kamara",
    name: "Alvin Kamara",
    position: "RB",
    team: "NO",
    number: "41",
    projected: 16.8,
    image: "/alvin-kamara-saints.jpg",
    tier: "green",
    stats: { rushing: 83, receiving: 82 },
    adp: 3.2,
    rank: 14,
  },

  // Wide Receivers
  {
    id: "tyreek-hill",
    name: "Tyreek Hill",
    position: "WR",
    team: "MIA",
    number: "10",
    projected: 19.5,
    image: "/tyreek-hill-dolphins.jpg",
    tier: "gold",
    stats: { receiving: 96, rushing: 55 },
    adp: 1.2,
    rank: 1,
  },
  {
    id: "jamarr-chase",
    name: "Ja'Marr Chase",
    position: "WR",
    team: "CIN",
    number: "1",
    projected: 17.8,
    image: "/ja-marr-chase-bengals-wide-receiver.jpg",
    tier: "orange",
    stats: { receiving: 92, rushing: 35 },
    adp: 1.8,
    rank: 2,
  },
  {
    id: "justin-jefferson",
    name: "Justin Jefferson",
    position: "WR",
    team: "MIN",
    number: "18",
    projected: 18.5,
    image: "/justin-jefferson-vikings.jpg",
    tier: "gold",
    stats: { receiving: 97, rushing: 30 },
    adp: 1.4,
    rank: 3,
  },
  {
    id: "george-pickens",
    name: "George Pickens",
    position: "WR",
    team: "PIT",
    number: "14",
    projected: 14.1,
    image: "/george-pickens-steelers-wide-receiver.jpg",
    tier: "gold",
    stats: { receiving: 85, rushing: 25 },
    adp: 4.5,
    rank: 4,
  },
  {
    id: "deebo-samuel",
    name: "Deebo Samuel",
    position: "WR",
    team: "SF",
    number: "19",
    projected: 13.5,
    image: "/deebo-samuel.jpg",
    tier: "orange",
    stats: { receiving: 88, rushing: 65 },
    adp: 5.2,
    rank: 5,
  },
  {
    id: "aj-brown",
    name: "A.J. Brown",
    position: "WR",
    team: "PHI",
    number: "11",
    projected: 18.2,
    image: "/aj-brown-eagles.jpg",
    tier: "gold",
    stats: { receiving: 94, rushing: 40 },
    adp: 1.6,
    rank: 6,
  },
  {
    id: "garrett-wilson",
    name: "Garrett Wilson",
    position: "WR",
    team: "NYJ",
    number: "5",
    projected: 16.5,
    image: "/garrett-wilson-jets.jpg",
    tier: "green",
    stats: { receiving: 89, rushing: 30 },
    adp: 2.8,
    rank: 7,
  },
  {
    id: "davante-adams",
    name: "Davante Adams",
    position: "WR",
    team: "NYJ",
    number: "17",
    projected: 17.2,
    image: "/davante-adams-jets-wide-receiver.jpg",
    tier: "green",
    stats: { receiving: 91, rushing: 25 },
    adp: 2.2,
    rank: 8,
  },
  {
    id: "stefon-diggs",
    name: "Stefon Diggs",
    position: "WR",
    team: "HOU",
    number: "1",
    projected: 16.8,
    image: "/stefon-diggs-texans-wide-receiver.jpg",
    tier: "green",
    stats: { receiving: 90, rushing: 20 },
    adp: 2.5,
    rank: 9,
  },
  {
    id: "puka-nacua",
    name: "Puka Nacua",
    position: "WR",
    team: "LAR",
    number: "17",
    projected: 16.2,
    image: "/puka-nacua-rams-wide-receiver.jpg",
    tier: "blue",
    stats: { receiving: 88, rushing: 30 },
    adp: 2.9,
    rank: 10,
  },
  {
    id: "mike-evans",
    name: "Mike Evans",
    position: "WR",
    team: "TB",
    number: "13",
    projected: 15.9,
    image: "/mike-evans-buccaneers-wide-receiver.jpg",
    tier: "green",
    stats: { receiving: 89, rushing: 15 },
    adp: 3.2,
    rank: 11,
  },
  {
    id: "chris-olave",
    name: "Chris Olave",
    position: "WR",
    team: "NO",
    number: "12",
    projected: 15.5,
    image: "/chris-olave-saints-wide-receiver.jpg",
    tier: "blue",
    stats: { receiving: 87, rushing: 20 },
    adp: 3.6,
    rank: 12,
  },
  {
    id: "dk-metcalf",
    name: "DK Metcalf",
    position: "WR",
    team: "SEA",
    number: "14",
    projected: 15.2,
    image: "/dk-metcalf-seahawks-wide-receiver.jpg",
    tier: "blue",
    stats: { receiving: 86, rushing: 25 },
    adp: 3.9,
    rank: 13,
  },
  {
    id: "brandon-aiyuk",
    name: "Brandon Aiyuk",
    position: "WR",
    team: "SF",
    number: "11",
    projected: 14.8,
    image: "/brandon-aiyuk-49ers-wide-receiver.jpg",
    tier: "orange",
    stats: { receiving: 85, rushing: 35 },
    adp: 4.3,
    rank: 14,
  },
  {
    id: "devonta-smith",
    name: "DeVonta Smith",
    position: "WR",
    team: "PHI",
    number: "6",
    projected: 14.5,
    image: "/devonta-smith-eagles-wide-receiver.jpg",
    tier: "green",
    stats: { receiving: 84, rushing: 20 },
    adp: 4.7,
    rank: 15,
  },
  {
    id: "nico-collins",
    name: "Nico Collins",
    position: "WR",
    team: "HOU",
    number: "12",
    projected: 16.1,
    image: "/nico-collins-texans.jpg",
    tier: "green",
    stats: { receiving: 88, rushing: 22 },
    adp: 3.1,
    rank: 16,
  },
  {
    id: "chris-godwin",
    name: "Chris Godwin",
    position: "WR",
    team: "TB",
    number: "14",
    projected: 15.3,
    image: "/chris-godwin-buccaneers.jpg",
    tier: "blue",
    stats: { receiving: 86, rushing: 18 },
    adp: 3.8,
    rank: 17,
  },
  {
    id: "cooper-kupp",
    name: "Cooper Kupp",
    position: "WR",
    team: "LAR",
    number: "10",
    projected: 16.7,
    image: "/cooper-kupp-rams.jpg",
    tier: "green",
    stats: { receiving: 90, rushing: 15 },
    adp: 2.7,
    rank: 18,
  },

  // Tight Ends
  {
    id: "travis-kelce",
    name: "Travis Kelce",
    position: "TE",
    team: "KC",
    number: "87",
    projected: 12.4,
    image: "/travis-kelce-chiefs-tight-end.jpg",
    tier: "blue",
    stats: { receiving: 90, blocking: 65 },
    adp: 3.5,
    rank: 1,
  },
  {
    id: "sam-laporta",
    name: "Sam LaPorta",
    position: "TE",
    team: "DET",
    number: "87",
    projected: 11.8,
    image: "/sam-laporta-lions.jpg",
    tier: "blue",
    stats: { receiving: 88, blocking: 70 },
    adp: 4.2,
    rank: 2,
  },
  {
    id: "mark-andrews",
    name: "Mark Andrews",
    position: "TE",
    team: "BAL",
    number: "89",
    projected: 11.2,
    image: "/mark-andrews-ravens.jpg",
    tier: "green",
    stats: { receiving: 86, blocking: 68 },
    adp: 4.8,
    rank: 3,
  },
  {
    id: "tj-hockenson",
    name: "T.J. Hockenson",
    position: "TE",
    team: "MIN",
    number: "87",
    projected: 10.5,
    image: "/tj-hockenson-vikings.jpg",
    tier: "green",
    stats: { receiving: 84, blocking: 72 },
    adp: 5.5,
    rank: 4,
  },
  {
    id: "george-kittle",
    name: "George Kittle",
    position: "TE",
    team: "SF",
    number: "85",
    projected: 10.8,
    image: "/george-kittle-49ers.jpg",
    tier: "green",
    stats: { receiving: 85, blocking: 75 },
    adp: 5.2,
    rank: 5,
  },
  {
    id: "evan-engram",
    name: "Evan Engram",
    position: "TE",
    team: "JAX",
    number: "17",
    projected: 10.2,
    image: "/evan-engram-jaguars.jpg",
    tier: "blue",
    stats: { receiving: 82, blocking: 65 },
    adp: 6.1,
    rank: 6,
  },
  {
    id: "kyle-pitts",
    name: "Kyle Pitts",
    position: "TE",
    team: "ATL",
    number: "8",
    projected: 9.8,
    image: "/kyle-pitts-falcons.jpg",
    tier: "blue",
    stats: { receiving: 83, blocking: 60 },
    adp: 6.8,
    rank: 7,
  },

  // Kickers
  {
    id: "austin-seibert",
    name: "Austin Seibert",
    position: "K",
    team: "WAS",
    number: "16",
    projected: 7.9,
    image: "/austin-seibert-commanders-kicker.jpg",
    tier: "purple",
    stats: {},
    adp: 14.2,
    rank: 1,
  },
  {
    id: "justin-tucker",
    name: "Justin Tucker",
    position: "K",
    team: "BAL",
    number: "9",
    projected: 8.5,
    image: "/justin-tucker-ravens.jpg",
    tier: "purple",
    stats: {},
    adp: 13.5,
    rank: 2,
  },
  {
    id: "harrison-butker",
    name: "Harrison Butker",
    position: "K",
    team: "KC",
    number: "7",
    projected: 8.2,
    image: "/harrison-butker-chiefs.jpg",
    tier: "purple",
    stats: {},
    adp: 13.8,
    rank: 3,
  },
  {
    id: "jake-moody",
    name: "Jake Moody",
    position: "K",
    team: "SF",
    number: "4",
    projected: 8.0,
    image: "/jake-moody-49ers.jpg",
    tier: "purple",
    stats: {},
    adp: 14.1,
    rank: 4,
  },
  {
    id: "brandon-aubrey",
    name: "Brandon Aubrey",
    position: "K",
    team: "DAL",
    number: "17",
    projected: 7.8,
    image: "/brandon-aubrey-cowboys.jpg",
    tier: "purple",
    stats: {},
    adp: 14.5,
    rank: 5,
  },

  // Defense/Special Teams
  {
    id: "49ers-dst",
    name: "49ers D/ST",
    position: "D/ST",
    team: "SF",
    number: "",
    projected: 6.3,
    image: "/san-francisco-49ers-defense-team-celebration.jpg",
    tier: "red",
    stats: { tackling: 88, coverage: 85 },
    adp: 12.5,
    rank: 1,
  },
  {
    id: "ravens-dst",
    name: "Ravens D/ST",
    position: "D/ST",
    team: "BAL",
    number: "",
    projected: 6.8,
    image: "/ravens-defense.jpg",
    tier: "red",
    stats: { tackling: 92, coverage: 88 },
    adp: 12.2,
    rank: 2,
  },
  {
    id: "cowboys-dst",
    name: "Cowboys D/ST",
    position: "D/ST",
    team: "DAL",
    number: "",
    projected: 6.5,
    image: "/cowboys-defense.jpg",
    tier: "red",
    stats: { tackling: 86, coverage: 84 },
    adp: 12.8,
    rank: 3,
  },
  {
    id: "bills-dst",
    name: "Bills D/ST",
    position: "D/ST",
    team: "BUF",
    number: "",
    projected: 6.6,
    image: "/bills-defense.jpg",
    tier: "red",
    stats: { tackling: 90, coverage: 86 },
    adp: 12.4,
    rank: 4,
  },
  {
    id: "browns-dst",
    name: "Browns D/ST",
    position: "D/ST",
    team: "CLE",
    number: "",
    projected: 6.4,
    image: "/browns-defense.jpg",
    tier: "red",
    stats: { tackling: 89, coverage: 85 },
    adp: 12.6,
    rank: 5,
  },
  {
    id: "micah-parsons",
    name: "Micah Parsons",
    position: "LB",
    team: "DAL",
    number: "11",
    projected: 8.2,
    image: "/micah-parsons-cowboys.jpg",
    tier: "red",
    stats: { tackling: 94, coverage: 78 },
    adp: 11.5,
    rank: 1,
  },
  {
    id: "tj-watt",
    name: "T.J. Watt",
    position: "LB",
    team: "PIT",
    number: "90",
    projected: 8.5,
    image: "/tj-watt-steelers.jpg",
    tier: "red",
    stats: { tackling: 96, coverage: 75 },
    adp: 11.2,
    rank: 2,
  },
  {
    id: "myles-garrett",
    name: "Myles Garrett",
    position: "DE",
    team: "CLE",
    number: "95",
    projected: 8.3,
    image: "/myles-garrett-browns.jpg",
    tier: "red",
    stats: { tackling: 95, coverage: 70 },
    adp: 11.4,
    rank: 3,
  },
  {
    id: "fred-warner",
    name: "Fred Warner",
    position: "LB",
    team: "SF",
    number: "54",
    projected: 8.1,
    image: "/fred-warner-49ers.jpg",
    tier: "red",
    stats: { tackling: 93, coverage: 88 },
    adp: 11.6,
    rank: 4,
  },
  {
    id: "chris-jones",
    name: "Chris Jones",
    position: "DT",
    team: "KC",
    number: "95",
    projected: 7.9,
    image: "/chris-jones-chiefs.jpg",
    tier: "red",
    stats: { tackling: 91, coverage: 72 },
    adp: 11.8,
    rank: 5,
  },
]

export const getPlayersByPosition = (position: string) => {
  return nflPlayerDatabase.filter((p) => p.position === position).sort((a, b) => a.rank - b.rank)
}

export const getTopProspects = (limit = 10) => {
  return nflPlayerDatabase.sort((a, b) => a.adp - b.adp).slice(0, limit)
}

export const searchPlayers = (query: string) => {
  const lowerQuery = query.toLowerCase()
  return nflPlayerDatabase.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.team.toLowerCase().includes(lowerQuery) ||
      p.position.toLowerCase().includes(lowerQuery),
  )
}
